language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
env:
    - DJANGO=1.6.6
    - DJANGO=1.7.1
install:
    - pip install Django==$DJANGO --use-mirrors
    - pip install pytest pytest-pep8 pytest-flakes django-pytest
    - pip install -r requirements.txt --use-mirrors
script:
    - python setup.py test
